[package]
name = "langs"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lang_support.path = "../lang_support"
utils.path = "../utils"
