[package]
name = "syntax_highlight"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tree-sitter = "0.24.7"
tree-sitter-highlight = "0.24.7"
tree-sitter-rust = "0.23.2"
anyhow.workspace = true
utils.path = "../utils"
