[workspace]
members = [
  "crates/cli",
  "crates/command",
  "crates/editor",
  "crates/key_binding",
  "crates/utils",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
authors = ["Yuta"]

[workspace.dependencies]
anyhow = "1.0.95"
arboard = "3.4.1"
crossterm = { version = "0.28.1", features = ["events"] }
fluent = "0.16.1"
fluent-templates = "0.13.0"
chrono = "0.4.39"
unicode-width = "0.2.0"
