[workspace]
members = [
  "crates/editor",
  "crates/key_binding",
  "crates/lang_support",
  "crates/utils",
  "crates/langs",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
authors = ["Yuta"]

[workspace.dependencies]
anyhow = "1.0.95"
arboard = "3.4.1"
crossterm = { version = "0.28.1", features = ["events"] }
clap = { version = "4.5.27", features = ["derive"] }
fluent = "0.16.1"
fluent-templates = "0.13.0"
chrono = "0.4.39"
unicode-width = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

[package]
name = "tui-studio"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
key_binding.path = "crates/key_binding"
editor.path = "crates/editor"
utils.path = "crates/utils"
fluent.workspace = true
fluent-templates.workspace = true
clap.workspace = true
chrono.workspace = true
tokio.workspace = true
async-trait.workspace = true
