[package]
name = "cli"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
editor.path = "../editor"
utils.path = "../utils"
