[package]
name = "utils"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
tokio.workspace = true
async-trait.workspace = true
