[package]
name = "side_view"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
utils.path = "../utils"
command.path = "../command"

[lib]
path = "src/side_view.rs"
